version: 2.1

jobs:
  build-and-push:
    docker:
      - image: docker:20.10.9
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t ayki2/docker-session:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login --username ayki2 --password-stdin
            docker push ayki2/docker-session:latest
  pull-and-deploy:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install SSH And Configure
          command: |
            echo $SSH_PRIVATE_KEY | base64 --decode > ./iskhak.pem
            chmod 400 iskhak.pem
      - run:
          name: Pull Image and Deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" -i ./iskhak.pem ubuntu@$HOST '
            sudo docker pull ayki2/docker-session:latest
            sudo docker run -d -p 80:2024 ayki2/docker-session:latest
            '
workflows:
  deploy:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
      - pull-and-deploy:
          requires:
            - build-and-push
          filters:
            branches:
              only: main